apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: csrx4-hpa
  namespace: default
spec:
  maxReplicas: 6 
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csrx4-byol
  targetCPUUtilizationPercentage: 60
