apiVersion: apps/v1
kind: Deployment
metadata:
  name: csrx3-byol-nlb
  labels:
    app: csrx3-byol-nlb
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: csrx3-byol-nlb
  template:
    metadata:
      name: csrx3-byol-nlb
      labels:
        app: csrx3-byol-nlb
      annotations:
        k8s.v1.cni.cncf.io/networks: br-51@eth1, br-52@eth2
    spec:      
      serviceAccountName: csrxpod
      containers:
      - name: csrx3-byol-nlb
        securityContext:
           privileged: true
        image: 298183613488.dkr.ecr.us-west-2.amazonaws.com/byol:0221 
        ports:
          - containerPort: 80
        env:
        - name: CSRX_SIZE
          value: "large"
        - name: CSRX_HUGEPAGES
          value: "no"
        - name: CSRX_PACKET_DRIVER
          value: "interrupt"
        - name: CSRX_FORWARD_MODE
          value: "routing"
        - name: CSRX_AUTO_ASSIGN_IP
          value: "yes"
        - name: CSRX_MGMT_PORT_REORDER
          value: "yes"
        - name: CSRX_TCP_CKSUM_CALC
          value: "yes"
        - name: CSRX_JUNOS_CONFIG
          value: "/var/jail/csrx_config"
        - name: CSRX_LICENSE_FILE
          value: "/var/jail/.csrx_license"
        volumeMounts:
        - name: disk
          mountPath: "/dev"
        - name: config
          mountPath: "/var/jail"
      volumes:
      - name: disk
        hostPath:
          path: /dev
          type: Directory
      - name: config
        configMap:
          name: cm-byol
          items:
          - key: csrx_config
            path: csrx_config
          - key: csrx_license
            path: .csrx_license
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csrx3-byol-nlb
  name: csrx3-byol-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
      app: csrx3-byol-nlb
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csrx3-byol-nlb
  name: csrx3-ssh
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
      app: csrx3-byol-nlb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
